# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-scratch" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "855625cfa128a237feeca9dc42c101b0b4f928b78d9eba23cd710bd47f81e190"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f818079b3c276c3eeb942f8823ff0a7018b733b549205452cd502221fa54b36"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a5d2b65e4d90184f51fb9a30bb3ea5ec1429e814a4712b17d005eb483a4aacc5"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43ee0a2519ab0cc45fe396198bcd46aab230a8eb7e0f15eca0b23ef182862958"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "herdr-scratch"
  desc "Scratch shell popup for herdr that detaches instead of closing"
  homepage "https://github.com/macintacos/herdr-scratch"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "herdr",
      "tmux",
    ]

  binary "bin/herdr-scratch"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/herdr-scratch"]
    end
    # Registration runs second because it executes the binary the strip
    # above just cleaned, and macOS will not run a quarantined one at all.
    linked = system_command "#{staged_path}/bin/herdr-scratch", args: ["link"],
                            env: { "HERDR_BIN_PATH" => "#{HOMEBREW_PREFIX}/bin/herdr" },
                            must_succeed: false, print_stdout: true
    unless linked.success?
      opoo "herdr-scratch link failed, so herdr is not running this build. " \
           "Run `herdr-scratch link` to register it."
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Bind a key in ~/.config/herdr/config.toml:

      [[keys.command]]
      key         = "prefix+'"
      type        = "plugin_action"
      command     = "user.scratch.toggle"
      description = "scratch shell"

    and apply it with:

      herdr server reload-config

    Installing and upgrading register this build with herdr for you. If the
    popup ever runs a build you have already upgraded past:

      herdr-scratch link
  EOS
end
