# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-scratch" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "60576cf882e44811e637a2d7030fc4b041b8cd5aa964974e72261ff18636df46"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a748bc97622989074066da685cb1fb6dccc8b26b770e1ffa2cb4e9753f367ad5"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "572e9896df9373812d02fb0136c8f62614806dcce444d95860a40ac2f894cb49"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d682f8be26a4f5aef594f505567cb06139227ccc6e88f28a1f26e690f376691"
      url "https://github.com/macintacos/herdr-scratch/releases/download/v#{version}/herdr-scratch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "herdr-scratch"
  desc "Scratch shell popup for herdr that detaches instead of closing"
  homepage "https://github.com/macintacos/herdr-scratch"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "herdr",
      "tmux",
    ]

  binary "bin/herdr-scratch"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/herdr-scratch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Register the plugin with herdr. Run it again after every upgrade:

      herdr-scratch link

    Then bind a key in ~/.config/herdr/config.toml:

      [[keys.command]]
      key         = "prefix+'"
      type        = "plugin_action"
      command     = "user.scratch.toggle"
      description = "scratch shell"

    and apply it with:

      herdr server reload-config
  EOS
end
