# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-reshape" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "66c3a3dc423a23d527d1f97bcedabee53ab8a4691718efec82dd1114f61dc8ec"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b6722cf32b41f38c72ae4b65a5bf6397bfcf8c5174df9362bcd4fbe8897efe2"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2701efaff71ffc043c958d8f267e61a2822488a0da90f7f7de2a06a8393b981f"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b01634bdab2576bedb438b764f3fa25e13542e7db8951b54b6fc9641b2a427d6"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_arm64.tar.gz"
    end
  end

  name "herdr-reshape"
  desc "Move the focused herdr pane, and best-fit a tab into an even grid"
  homepage "https://github.com/macintacos/herdr-reshape"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "herdr",
    ]

  binary "bin/herdr-reshape"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/herdr-reshape"]
    end
    root = Pathname.new("#{HOMEBREW_PREFIX}/share/herdr-reshape")
    FileUtils.rm_r(root) if root.exist?
    root.mkpath
    FileUtils.cp_r(["#{staged_path}/bin", "#{staged_path}/herdr-plugin.toml"], root)
  end

  # No zap stanza required

  caveats <<~EOS
    Bind the five actions in ~/.config/herdr/config.toml, one block each:

      [[keys.command]]
      key         = "prefix+="
      type        = "plugin_action"
      command     = "user.reshape.fit"
      description = "best-fit the tab"

    The other four action ids are user.reshape.move-left,
    user.reshape.move-right, user.reshape.move-up and
    user.reshape.move-down. Apply them with:

      herdr server reload-config

    Then register the plugin with herdr — once, not per upgrade.
    Every upgrade refreshes what sits behind this path:

      herdr plugin link "$(brew --prefix)/share/herdr-reshape"

    Removing it takes three steps, because brew owns only the
    first: the plugin root is written by this cask's own
    post-install rather than installed by brew, and herdr's
    registration outlives the uninstall either way.

      brew uninstall --cask herdr-reshape
      herdr plugin unlink user.reshape
      rm -rf "$(brew --prefix)/share/herdr-reshape"
  EOS
end
