# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-reshape" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "16d0aaab82c6bfe51e71ad3d95aa7579ef9ad1a95358013bec9ce83123bcc460"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a844aa04e6d66594920864052522448eb7d6f259dea329814f6efc7271eb92bf"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b727f473e729a4987d563d595764f3d5716addca5d2edf7ce23bd4a26127740a"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29f474aa90c1ba461f77721bcd1dff2c3983dc6e986c86f5e2f97804b79fa423"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_arm64.tar.gz"
    end
  end

  name "herdr-reshape"
  desc "Move the focused herdr pane, and best-fit a tab into an even grid"
  homepage "https://github.com/macintacos/herdr-reshape"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "herdr",
    ]

  binary "bin/herdr-reshape"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/herdr-reshape"]
    end
  end

  zap trash: [
      "~/.local/share/herdr-reshape",
    ]

  caveats <<~EOS
    Bind the five actions in ~/.config/herdr/config.toml, one block each:

      [[keys.command]]
      key         = "prefix+="
      type        = "plugin_action"
      command     = "user.reshape.fit"
      description = "best-fit the tab"

    The other four action ids are user.reshape.move-left,
    user.reshape.move-right, user.reshape.move-up and
    user.reshape.move-down. Apply them with:

      herdr server reload-config

    Then register this build with herdr — after every install and
    upgrade, since nothing else points herdr at it:

      herdr-reshape link

    Removing it takes both halves: --zap for the copy link made,
    which lives outside the cask, and the unlink for herdr's
    registration of it, which survives either way.

      brew uninstall --zap --cask herdr-reshape
      herdr plugin unlink user.reshape
  EOS
end
