# This file was generated by GoReleaser. DO NOT EDIT.
cask "herdr-reshape" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "abd841a302d691cd496576a4229402504cf0bfb00280907727fcf32806df634b"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebb0722771d01c9d9aded5188b5e35e0f49bb577a837966e719bc5b19c6e6ac1"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c52cd570d9670d968823867ed5ae3f24d80d5ecb7d81e6a796a157b3fab52e62"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "55317bbbc2c983f2e2f21ef91a7e0f7bb15291df74cf33b82e980324cc9d2e70"
      url "https://github.com/macintacos/herdr-reshape/releases/download/v#{version}/herdr-reshape_#{version}_linux_arm64.tar.gz"
    end
  end

  name "herdr-reshape"
  desc "Move the focused herdr pane, and best-fit a tab into an even grid"
  homepage "https://github.com/macintacos/herdr-reshape"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "herdr",
    ]

  binary "bin/herdr-reshape"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/herdr-reshape"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Bind the five actions in ~/.config/herdr/config.toml, one block each:

      [[keys.command]]
      key         = "prefix+="
      type        = "plugin_action"
      command     = "user.reshape.fit"
      description = "best-fit the tab"

    The other four action ids are user.reshape.move-left,
    user.reshape.move-right, user.reshape.move-up and
    user.reshape.move-down. Apply them with:

      herdr server reload-config

    Then register this build with herdr — after every install and
    upgrade, since nothing else points herdr at it:

      herdr-reshape link
  EOS
end
