# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrReshape < Formula
  desc "Move the focused herdr pane, and best-fit a tab into an even grid"
  homepage "https://github.com/macintacos/herdr-reshape"
  version "0.3.0"
  license "MIT"

  depends_on "herdr"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.0/herdr-reshape_0.3.0_darwin_amd64.tar.gz"
      sha256 "84f34b29b73c84e7e391de871bc39e90fff560608e9f748fd2855aea1bc016bd"

      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.0/herdr-reshape_0.3.0_darwin_arm64.tar.gz"
      sha256 "a7bbeb106c205dc8899bcddb5842531644acc458283e18d5d8dc57a6b2e14cae"

      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.0/herdr-reshape_0.3.0_linux_amd64.tar.gz"
      sha256 "dd44fdb09da7cdefd8b70bbf1862e2cb647eec51ab0df9e80c3619101dd88d1b"
      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.0/herdr-reshape_0.3.0_linux_arm64.tar.gz"
      sha256 "416684acb618f4a62cba7d3667a44fbee39c998dabb4a9404bfa4b0d8ba49871"
      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
  end

  def post_install
    root = HOMEBREW_PREFIX/"share/herdr-reshape"
    rm_r root if root.exist?
    root.mkpath
    cp_r [libexec/"bin", libexec/"herdr-plugin.toml"], root
  end

  def caveats
    <<~EOS
      Bind the five actions in ~/.config/herdr/config.toml, one block each:

        [[keys.command]]
        key         = "prefix+="
        type        = "plugin_action"
        command     = "user.reshape.fit"
        description = "best-fit the tab"

      The other four action ids are user.reshape.move-left,
      user.reshape.move-right, user.reshape.move-up and
      user.reshape.move-down. Apply them with:

        herdr server reload-config

      Then register the plugin with herdr — once, not per upgrade.
      Every upgrade refreshes what sits behind this path:

        herdr plugin link "$(brew --prefix)/share/herdr-reshape"

      Removing it takes three steps, because brew owns only the
      first: a formula has no zap, and herdr's registration
      outlives the uninstall either way.

        brew uninstall herdr-reshape
        herdr plugin unlink user.reshape
        rm -rf "$(brew --prefix)/share/herdr-reshape"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herdr-reshape --version")
  end
end
