# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrReshape < Formula
  desc "Move the focused herdr pane, and best-fit a tab into an even grid"
  homepage "https://github.com/macintacos/herdr-reshape"
  version "0.3.1"
  license "MIT"

  depends_on "herdr"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.1/herdr-reshape_0.3.1_darwin_amd64.tar.gz"
      sha256 "97fc3b49ad7b0e6fd727db70baf50eb5c9fcf1110c8eee70447fb5fe91ff034d"

      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.1/herdr-reshape_0.3.1_darwin_arm64.tar.gz"
      sha256 "18b7952e3aa5d93fc16f181c0fdbf64be286a44fb4699d8a2db72cf18058b7c5"

      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.1/herdr-reshape_0.3.1_linux_amd64.tar.gz"
      sha256 "fee595a5e5d416a9b646497433b2d84ba385e9b2b2d5e6c4cd86f3b065d3ed36"
      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/macintacos/herdr-reshape/releases/download/v0.3.1/herdr-reshape_0.3.1_linux_arm64.tar.gz"
      sha256 "221f6a782772868fab994dfcdbbad0ab5e06c3c842567d93cdf2780f86722b2e"
      define_method(:install) do
        libexec.install "bin", "herdr-plugin.toml"
        bin.install_symlink libexec/"bin/herdr-reshape"
        prefix.install "LICENSE"
      end
    end
  end

  def post_install
    root = HOMEBREW_PREFIX/"share/herdr-reshape"
    rm_r root if root.exist?
    root.mkpath
    cp_r [libexec/"bin", libexec/"herdr-plugin.toml"], root
  end

  def caveats
    <<~EOS
      Bind the five actions in ~/.config/herdr/config.toml, one block each:

        [[keys.command]]
        key         = "prefix+="
        type        = "plugin_action"
        command     = "user.reshape.fit"
        description = "best-fit the tab"

      The other four action ids are user.reshape.move-left,
      user.reshape.move-right, user.reshape.move-up and
      user.reshape.move-down. Apply them with:

        herdr server reload-config

      Then register the plugin with herdr — once, not per upgrade.
      Every upgrade refreshes what sits behind this path:

        herdr plugin link "$(brew --prefix)/share/herdr-reshape"

      Removing it takes three steps, because brew owns only the
      first: a formula has no zap, and herdr's registration
      outlives the uninstall either way.

        brew uninstall herdr-reshape
        herdr plugin unlink user.reshape
        rm -rf "$(brew --prefix)/share/herdr-reshape"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herdr-reshape --version")
  end
end
